[package]
name = "aoc"
version = "0.1.0"
authors = ["Arpit Saxena <arpit.saxena2000@yahoo.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
